version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: sqlite
    ports:
      - '1337:1337'
    volumes:
      - ./strapi-app:/srv/app
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - '8080:80'
